version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3006:3006"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
